### ISSUE TITLE
Add main packages for biodiversity/spatial analysis

### ISSUE THREAD

**Issue by silasprincipe** [iobis/obis-hub#2]
We need to make a list of R and Python packages that should be available for the users as default. I will start a list here, but we need to collect more suggestions:

### R

- [x] tidyverse
- [x] terra
- [x] sf
- [x] stars
- [x] spatstat

### Python
- [x] xarray
- [x] zarr
- [x] netCDF4
- [x] pandas
- [x] numpy
- [x] scikit-learn
- [x] geopandas

**Comment by pieterprovoost** [comment]
I have added a few of the R packages for testing and will add the rest as well, see https://github.com/iobis/jupyterhub-deploy-docker/blob/obis/basic-example/Dockerfile.obis-notebook
