### ISSUE TITLE
is there a data dictionary for parquet column names?

### ISSUE THREAD

**Issue by sformel-usgs** [iobis/obis-hub#3]
Is there a dictionary for the column names in the parquet snapshot of OBIS? I imagine that will be a handy resource to new people who might not be familiar with all the data included in the snapshot. 

I looked but couldn't easily find it.  If so, we should link that in the jupyterhub documentation.  If not, I'd be willing to help by create one.

**Comment by silasprincipe** [comment]
Hi @sformel-usgs, sorry for the long delay in answering here. Yes, on the full export page there is a description of all the columns available: https://obis.org/data/access/

**Comment by sformel-usgs** [comment]
Yes there is. 🤦‍♂️ I can't believe I didn't see that. Thanks for the answer!
